name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Version of the tag
        id: version
        run: echo ::set-output name=value::$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/^v//')

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ldes-replicator:${{ steps.version.outputs.value }}

      - name: Push the Docker image
        run: docker push ghcr.io/osoc21/ldes-replicator:${{ steps.version.outputs.value }}
